apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: ping-source-broker
spec:
  schedule: "*/1 * * * *"
  jsonData: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: my-broker
